add -> git config --global user.name ""
bikol/DINO202223 pull request #2
Opened 2022-10-31 16:44 UTC by mdokusV

2022-10-31 16:50 UTC, pawelFelcyn requested changes

2022-10-31 16:50 UTC, pawelFelcyn commented on index.html
> +    git config --global user.name "" : zmienia nazwę, która jest powiązana z commitami w Git-cie
Możemy trzymać się jednej konwencji? Np. piszemy całym zdaniem Komenda a - robi coś?

2022-10-31 16:52 UTC, mdokusV commented on index.html
> +    git config --global user.name "" : zmienia nazwę, która jest powiązana z commitami w Git-cie
Proponuję jednak " : ". Jest kilka komend które zawierają już " - " jako swoją część

2022-10-31 16:54 UTC, pawelFelcyn commented on index.html
> +    git config --global user.name "" : zmienia nazwę, która jest powiązana z commitami w Git-cie
Ok, proponuję "Komenda a: wykonuje coś."

2022-11-04 14:30 UTC, bikol requested changes
proszę zmergować z ocnym masterem

2022-11-09 16:13 UTC, merged