Update index.html
bikol/DINO202223 pull request #4
Opened 2022-11-06 02:12 UTC by xArtem1

add command "git commit <filename>"

2022-11-28 11:07 UTC, bikol requested changes
proszę zrobic merge z obecnym stanem

2022-11-29 19:47 UTC, xArtem1 commented
> proszę zrobic merge z obecnym stanem

gotowe

2022-11-30 13:33 UTC, bikol requested changes
ponownie jest konflikt, prosze o merge

2022-11-30 15:05 UTC, xArtem1 commented
> ponownie jest konflikt, prosze o merge

gotowe

2022-12-21 09:16 UTC, merged